image:
  file: .gitpod.Dockerfile

tasks:
  - name: "ShirayukiProject Container"
    command: |
      echo "Trying to execute change users script..."
      exec bash
      clean

vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

# Ports section (if your app exposes ports, for example)
ports:
  - port: 3000
    onOpen: open-preview
